services:
  postgres-user:
    image: postgres:15
    container_name: eventiq-postgres-user
    environment:
      POSTGRES_DB: eventiq_user
      POSTGRES_USER: eventiq
      POSTGRES_PASSWORD: eventiq123
    ports:
      - "5432:5432"
    volumes:
      - postgres-user-data:/var/lib/postgresql/data
    networks:
      - eventiq-net

  postgres-org:
    image: postgres:15
    container_name: eventiq-postgres-org
    environment:
      POSTGRES_DB: eventiq_org
      POSTGRES_USER: eventiq
      POSTGRES_PASSWORD: eventiq123
    ports:
      - "5433:5432"
    volumes:
      - postgres-org-data:/var/lib/postgresql/data
    networks:
      - eventiq-net

  postgres-event:
    image: postgres:15
    container_name: eventiq-postgres-event
    environment:
      POSTGRES_DB: eventiq_event
      POSTGRES_USER: eventiq
      POSTGRES_PASSWORD: eventiq123
    ports:
      - "5434:5432"
    volumes:
      - postgres-event-data:/var/lib/postgresql/data
    networks:
      - eventiq-net

  user-service:
    image: user-service
    build:
      context: .
      dockerfile: Eventiq.UserService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8081
      ConnectionStrings__Postgres: >
        Host=postgres-user;
        Port=5432;
        Database=eventiq_user;
        Username=eventiq;
        Password=eventiq123;
        Ssl Mode=Disable;
    depends_on:
      postgres-user:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./keys:/app/keys:ro
    networks:
      - eventiq-net
  org-service:
      image: org-service
      build:
        context: .
        dockerfile: Eventiq.OrganizationService/Dockerfile
      environment:
        ASPNETCORE_ENVIRONMENT: Development
        ASPNETCORE_URLS: http://+:8082
        ConnectionStrings__Postgres: >
          Host=postgres-org;
          Port=5432;
          Database=eventiq_org;
          Username=eventiq;
          Password=eventiq123;
          Ssl Mode=Disable;
      depends_on:
        postgres-org:
          condition: service_started
        rabbitmq:
          condition: service_healthy
      volumes:
        - ./keys:/app/keys:ro
      networks:
        - eventiq-net

  event-service:
    image: event-service
    build:
      context: .
      dockerfile: Eventiq.EventService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8083
      ConnectionStrings__Postgres: >
        Host=postgres-event;
        Port=5432;
        Database=eventiq_event;
        Username=eventiq;
        Password=eventiq123;
        Ssl Mode=Disable;
    depends_on:
      postgres-event:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./keys:/app/keys:ro
    networks:
      - eventiq-net

  api-gateway:
    image: api-gateway
    build:
      context: .
      dockerfile: Eventiq.ApiGateway/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - user-service
      - org-service
      - event-service
    ports:
      - "5001:8080"
    volumes:
      - ./keys:/app/keys:ro
    networks:
      - eventiq-net

  email-service:
    image: email-service
    build:
      context: .
      dockerfile: Eventiq.EmailService/Dockerfile
    environment:
      DOTNET_ENVIRONMENT: Development
      ASPNETCORE_ENVIRONMENT: Development
      RabbitMq__ConnectionString: amqp://eventiq:eventiq123@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - eventiq-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: eventiq
      RABBITMQ_DEFAULT_PASS: eventiq123
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - eventiq-net
  contracts:
    image:  contracts
    build:
      context: .
      dockerfile: Eventiq.Contracts/Dockerfile

volumes:
  postgres-user-data:
  postgres-org-data:
  postgres-event-data:

networks:
  eventiq-net:
    driver: bridge

